export const Categories : Array<{title: string, value: string}> = [{
    title: "Arts",
    value: "Arts & Photography"
},
{ title: "Biographies", value: "Biographies" },
{ title: "Business", value: "Business & Money" },
{ title: "Calendriers", value: "Calendars" },
{ title: "Enfant", value: "Children's Books" },
{ title: "Comics", value: "Comics & Graphic Novels" },
{ title: "Informatique", value: "Computers & Technology" },
{ title: "Cuisine", value: "Cookbooks, Food & Wine" },
{ title: "Loisirs", value: "Crafts, Hobbies & Home" },
{ title: "Education", value: "Education & Teaching" },
{ title: "Transport", value: "Engineering & Transportation" },
{ title: "Santé", value: "Health, Fitness & Dieting" },
{ title: "Histoire", value: "History" },
{ title: "Humour", value: "Humor & Entertainment" },
{ title: "Justice", value: "Law" },
{ title: "Lgbt", value: "LGBTQ+ Books" },
{ title: "Litterature", value: "Literature & Fiction" },
{ title: "Medecine", value: "Medical Books" },
{ title: "Polar", value: "Mystery, Thriller & Suspense" },
{ title: "Parentalité", value: "Parenting & Relationships" },
{ title: "Politique", value: "Politics & Social Sciences" },
{ title: "Reference", value: "Reference" },
{ title: "Religion", value: "Religion & Spirituality" },
{ title: "Romance", value: "Romance" },
{ title: "Sciences", value: "Science & Math" },
{ title: "Science Fiction", value: "Science Fiction & Fantasy" },
{ title: "Developpement personnnel", value: "Self-Help" },
{ title: "Sports", value: "Sports & Outdoors" },
{ title: "Etudiant", value: "Teen & Young Adul Books" },
{ title: "Preparation aux tests", value: "Test Preparation" },
{ title: "Voyage", value: "Travel" }
]